export const getFbrPayload = (
  invoice,
  items,
  isProd,
  customers,
  formatDateForInput,
) => {
  const customer = customers.find((c) => c.id === invoice.customer_id);
  const roundTo4Num = (num) => Math.round(roundTo2Num(num || 0) * 10000) / 10000;
const roundTo2Num = (num) => Math.round(roundTo2Num(num || 0) * 100) / 100;
  switch (invoice.scenario_code) {
    case "SN001":
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        //scenarioId: invoice.scenario_code,
        ...(!isProd && { scenarioId: invoice.scenario_code }),
        buyerRegistrationType: invoice.buyerType,
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0.0,
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || "",
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      };
    case "SN002":
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        //scenarioId: invoice.scenario_code,
        ...(!isProd && { scenarioId: invoice.scenario_code }),
        buyerRegistrationType: invoice.buyerType,
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0.0,
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || "",
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      };
    case "SN003":
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        //scenarioId: invoice.scenario_code,
        ...(!isProd && { scenarioId: invoice.scenario_code }),
        buyerRegistrationType: invoice.buyerType,
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0.0,
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || 0,
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      };
    case "SN004":
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        //scenarioId: invoice.scenario_code,
        ...(!isProd && { scenarioId: invoice.scenario_code }),
        buyerRegistrationType: invoice.buyerType,
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0,
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || 0,
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      };
    case "SN005":
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        //scenarioId: invoice.scenario_code,
        ...(!isProd && { scenarioId: invoice.scenario_code }),
        buyerRegistrationType: invoice.buyerType,
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0,
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || "",
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      };
    case "SN006":
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        //scenarioId: invoice.scenario_code,
        ...(!isProd && { scenarioId: invoice.scenario_code }),
        buyerRegistrationType: invoice.buyerType,
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0,
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || "",
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      };
    case "SN007":
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        //scenarioId: invoice.scenario_code,
        ...(!isProd && { scenarioId: invoice.scenario_code }),
        buyerRegistrationType: invoice.buyerType,
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || 0,
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0,
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      };
    case "SN008":
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        //scenarioId: invoice.scenario_code,
        ...(!isProd && { scenarioId: invoice.scenario_code }),
        buyerRegistrationType: invoice.buyerType,
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0.0,
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || 0,
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      };
    case "SN009":
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        //scenarioId: invoice.scenario_code,
        ...(!isProd && { scenarioId: invoice.scenario_code }),
        buyerRegistrationType: invoice.buyerType,
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0.0,
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || 0,
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      };
    case "SN010":
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        //scenarioId: invoice.scenario_code,
        ...(!isProd && { scenarioId: invoice.scenario_code }),
        buyerRegistrationType: invoice.buyerType,
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0.0,
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || 0,
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      };
    case "SN011":
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        dataSource: "",
        //scenarioId: invoice.scenario_code,
        ...(!isProd && { scenarioId: invoice.scenario_code }),
        buyerRegistrationType: invoice.buyerType,
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0.0,
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || 0,
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      };
    case "SN012":
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        //scenarioId: invoice.scenario_code,
        ...(!isProd && { scenarioId: invoice.scenario_code }),
        buyerRegistrationType: invoice.buyerType,
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0.0,
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || 0,
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      };
    case "SN013":
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        //scenarioId: invoice.scenario_code,
        ...(!isProd && { scenarioId: invoice.scenario_code }),
        buyerRegistrationType: invoice.buyerType,
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0.0,
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || 0,
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      };
    case "SN014":
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        //scenarioId: invoice.scenario_code,
        ...(!isProd && { scenarioId: invoice.scenario_code }),
        buyerRegistrationType: invoice.buyerType,
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0.0,
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || 0,
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      };
    case "SN015":
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        //scenarioId: invoice.scenario_code,
        ...(!isProd && { scenarioId: invoice.scenario_code }),
        buyerRegistrationType: invoice.buyerType,
        additional1: "",
        additional2: "",
        additional3: "",
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0.0,
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || 0,
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      };
    case "SN016":
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        //scenarioId: invoice.scenario_code,
        ...(!isProd && { scenarioId: invoice.scenario_code }),
        buyerRegistrationType: invoice.buyerType,
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0.0,
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || 0,
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      };
    case "SN017":
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        //scenarioId: invoice.scenario_code,
        ...(!isProd && { scenarioId: invoice.scenario_code }),
        buyerRegistrationType: invoice.buyerType,
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0.0,
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || 0,
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      };
    case "SN018":
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        //scenarioId: invoice.scenario_code,
        ...(!isProd && { scenarioId: invoice.scenario_code }),
        buyerRegistrationType: invoice.buyerType,
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0.0,
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || 0,
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      };
    case "SN019":
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        buyerRegistrationType: invoice.buyerType,
        //scenarioId: invoice.scenario_code,
        ...(!isProd && { scenarioId: invoice.scenario_code }),
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0.0,
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || 0,
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      };
    case "SN020":
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        buyerRegistrationType: invoice.buyerType,
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        //scenarioId: invoice.scenario_code,
        ...(!isProd && { scenarioId: invoice.scenario_code }),
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0.0,
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || 0,
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      };
    case "SN021":
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        buyerRegistrationType: invoice.buyerType,
        //scenarioId: invoice.scenario_code,
        ...(!isProd && { scenarioId: invoice.scenario_code }),
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0.0,
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || 0,
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      };
    case "SN022":
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        buyerRegistrationType: invoice.buyerType,
        //scenarioId: invoice.scenario_code,
        ...(!isProd && { scenarioId: invoice.scenario_code }),
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0.0,
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || 0,
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      };
    case "SN023":
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        buyerRegistrationType: invoice.buyerType,
        //scenarioId: invoice.scenario_code,
        ...(!isProd && { scenarioId: invoice.scenario_code }),
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0.0,
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || 0,
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      };
    case "SN024":
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        buyerRegistrationType: invoice.buyerType,
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        //scenarioId: invoice.scenario_code,
        ...(!isProd && { scenarioId: invoice.scenario_code }),
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0.0,
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || 0,
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      };
    case "SN025":
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        buyerRegistrationType: invoice.buyerType,
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        //scenarioId: invoice.scenario_code,
        ...(!isProd && { scenarioId: invoice.scenario_code }),
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0.0,
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || "",
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      };
    case "SN026":
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        buyerRegistrationType: invoice.buyerType,
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        //scenarioId: invoice.scenario_code,
        ...(!isProd && { scenarioId: invoice.scenario_code }),
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0.0,
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || 0,
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      };
    case "SN027":
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        buyerRegistrationType: invoice.buyerType,
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        //scenarioId: invoice.scenario_code,
        ...(!isProd && { scenarioId: invoice.scenario_code }),
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0.0,
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || 0,
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      };
    case "SN028":
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        buyerRegistrationType: invoice.buyerType,
        //scenarioId: invoice.scenario_code,
        ...(!isProd && { scenarioId: invoice.scenario_code }),
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0.0,
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || "",
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      };
    default:
      return {
        invoiceType: invoice.saleType,
        invoiceDate: formatDateForInput(invoice.invoice_date),
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        sellerBusinessName: sessionStorage.getItem("sellerBusinessName") || "",
        sellerProvince: invoice.sellerProvince,
        sellerNTNCNIC: sessionStorage.getItem("sellerNTNCNIC") || "",
        sellerAddress: sessionStorage.getItem("sellerAddress") || "",
        buyerNTNCNIC: customer.ntn || customer.cnic || "",
        buyerBusinessName: invoice.customer_name,
        buyerProvince: invoice.buyerProvince,
        buyerAddress: customer.locations[0]?.address || "",
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        buyerRegistrationType: invoice.buyerType,
        invoiceRefNo: invoice.fbrInvoiceRefNo ?? "",
        sourceInvoiceNo: invoice.internal_inv_ref_no,
        items: items.map((item) => ({
          hsCode: item.hsCode,
          productDescription: item.description,
          rate: item.rateDesc,
          uoM: item.unit,
          quantity: roundTo4Num(item.qty),
          totalValues: roundTo2Num(item.totalValues),
          valueSalesExcludingST: roundTo2Num(item.valueSalesExcludingST),
          fixedNotifiedValueOrRetailPrice:
            roundTo2Num(item.fixedNotifiedValueOrRetailPrice) || 0.0,
          salesTaxApplicable: roundTo2Num(item.salesTaxApplicable) || 0,
          salesTaxWithheldAtSource: roundTo2Num(item.salesTaxWithheldAtSource) || 0,
          extraTax: roundTo2Num(item.extraTax) || "",
          furtherTax: roundTo2Num(item.furtherTax) || 0,
          sroScheduleNo: item.sroScheduleNo || "",
          fedPayable: roundTo2Num(item.fedPayable) || 0,
          discount: roundTo2Num(item.discount) || 0,
          saleType: item.TransactionType || "",
          sroItemSerialNo: item.sroItemSerialNo || "",
        })),
      }
  }
};
